name: ext-yasd

on: [push, pull_request]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install
  
  build-centos-latest:
    runs-on: centos-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install

  build-macos-latest:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install && php -d zend_extension=yasd.so --ri yasd
