name: ext-yasd

on: [push, pull_request]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install && php -d zend_extension=yasd.so --ri yasd

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install && php -d zend_extension=yasd.so --ri yasd

  build-macos-latest:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: phpize && ./configure && make clean && make -j$(sysctl -n hw.ncpu) && sudo make install && php -d zend_extension=yasd.so --ri yasd
