name: ext-yasd

on: [push, pull_request]

jobs:
  build-yasd:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, macos-latest]
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - if: startsWith(runner.os, 'Linux')
      run: |
        sudo apt-get install libboost-all-dev
    - if: startsWith(runner.os, 'macOS')
      run: |
        brew install boost
    - name: Build extension
      run: |
        phpize
        ./configure
        make clean
        make -j$(sysctl -n hw.ncpu)
        sudo make install
        # php -d zend_extension=$PWD/modules/yasd.so --ri yasd
